//
// Created by jesse on 21/12/2023.
//

#ifndef BRACKOCALYPSE_ALIGNMENT_HPP
#define BRACKOCALYPSE_ALIGNMENT_HPP

enum Alignment {
    LEFTTOP,
    LEFTCENTER,
    LEFTBOTTOM,
    CENTERTOP,
    CENTERCENTER,
    CENTERBOTTOM,
    RIGHTTOP,
    RIGHTCENTER,
    RIGHTBOTTOM
    
};

#endif //BRACKOCALYPSE_ALIGNMENT_HPP
